import type { StackCategory } from "@/lib/types";

export const stack: StackCategory[] = [
  {
    category: "Programming Languages",
    items: [
      "Java",
      "C++",
      "C",
      "Python",
      "JavaScript",
      "TypeScript",
      "SQL",
      "Dart",
      "Swift",
      "GDScript",
      "HTML/CSS",
      "TailwindCSS",
    ],
  },
  {
    category: "Frameworks & Libraries",
    items: [
      "Spring Boot",
      "Spring WebFlux",
      "FastAPI",
      "Flask",
      "Next.js",
      "ReactJS",
      "Flutter",
      "Godot",
      "Plotly",
      "Pandas",
      "NumPy",
      "SwiftUI",
      "AVFoundation",
      "Core Image",
      "Metal",
      "Redux",
      "Vite",
      "Spring Batch",
      "JPA / Hibernate",
      "scikit-learn",
    ],
  },
  {
    category: "AI & LLM",
    items: [
      "AWS Bedrock",
      "Claude / Anthropic API",
      "Amazon Titan Embeddings",
      "OpenAI API",
      "Perplexity API",
      "IBM watsonx",
      "ChromaDB",
      "VAPI.ai",
    ],
  },
  {
    category: "Databases & Messaging",
    items: ["MySQL", "MongoDB", "Redis", "Firebase", "Kafka"],
  },
  {
    category: "Tools",
    items: [
      "Git",
      "Postman",
      "Jira",
      "Confluence",
      "Figma",
      "GA4",
      "Selenium",
      "XcodeGen",
      "Flyway",
      "Testcontainers",
      "k6",
      "Vitest",
      "JUnit",
    ],
  },
  {
    category: "Cloud & DevOps",
    items: [
      "Docker",
      "GitHub Actions",
      "Nginx",
      "GCP",
      "AWS",
      "Cloudflare",
      "Vercel",
      "Netlify",
      "AWS EC2 / RDS",
      "Cloudflare R2",
      "Kubernetes",
      "GCP Secret Manager",
    ],
  },
];
