import type { WorkItem } from "@/lib/types";

// All shipped work, in display order. Every entry has `hasCaseStudy: true` and
// gets a write-up at /work/<slug> (bodies in content/work/<slug>.tsx). `index`
// is the printed row number, so it must stay 1..n in array order.
export const work: WorkItem[] = [
  {
    slug: "coffeebyme",
    index: 1,
    title: "CoffeeByMe",
    year: "2026",
    role: "Solo developer · Technical lead",
    status: "Live",
    metric: "1.1K+ MAU",
    summary:
      "AI-powered coffee discovery platform for the US and Korean markets — built solo, from a Python ingestion pipeline to a production recommendation engine.",
    tags: ["product", "ai"],
    stack: [
      "Java",
      "Spring Boot",
      "AWS Bedrock",
      "Claude Haiku 4.5",
      "Titan Embeddings",
      "MySQL",
      "Redis",
      "Docker",
      "GitHub Actions",
    ],
    href: "/work/coffeebyme",
    demoHref: "https://coffeebyme.com",
    githubHref: "https://github.com/driffe/coffee",
    hasCaseStudy: true,
    thumbnail: "/work/coffeebyme/hero-paint.webp",
  },
  {
    slug: "pilm",
    index: 2,
    title: "Pilm",
    year: "2026",
    role: "Solo developer",
    status: "App Store",
    metric: "3.2K+ downloads",
    summary:
      "A film-preset iOS camera app that shoots 9:16 and 16:9 simultaneously from one sensor and renders both live — entirely on-device.",
    tags: ["mobile"],
    stack: ["Swift", "SwiftUI", "AVFoundation", "Core Image", "Metal"],
    href: "/work/pilm",
    demoHref: "https://apps.apple.com/us/app/pilm-camera/id6781464671",
    githubHref: "https://github.com/driffe/pilm",
    hasCaseStudy: true,
    thumbnail: "/work/pilm/thumb.webp",
  },
  {
    slug: "excel-stock",
    index: 3,
    title: "excel-stock",
    year: "2026",
    role: "Solo developer",
    status: "Live",
    metric: "~500 visitors/mo",
    summary:
      "A live stock watchlist disguised as a Microsoft Excel spreadsheet, hardened with a keyless batched proxy so upstream load never scales with viewers.",
    tags: ["web", "tools"],
    stack: ["Vite", "React", "TypeScript", "Vercel Functions", "Stooq", "Finnhub"],
    href: "/work/excel-stock",
    demoHref: "https://excel-stock.vercel.app/",
    githubHref: "https://github.com/driffe/excel-stock",
    hasCaseStudy: true,
    thumbnail: "/work/excel-stock/screen.webp",
  },
  {
    slug: "ibm-nba-hub",
    index: 4,
    title: "IBM NBA Hub — IBM SkillsBuild",
    year: "2025",
    role: "Team lead, 3-person team",
    award: "1st · AI in Sports, 300+ teams",
    summary: "AI-powered NBA fan platform built on IBM watsonx Granite models.",
    tags: ["ai", "product"],
    stack: ["Python", "FastAPI", "IBM Watsonx", "AI/ML"],
    href: "/work/ibm-nba-hub",
    demoHref: "https://youtu.be/GOdMPxPy90w",
    githubHref: "https://github.com/driffe/IBM",
    hasCaseStudy: true,
    thumbnail: "/work/ibm-nba-hub/pitch-cover.webp",
  },
  {
    slug: "project-loki",
    index: 5,
    title: "Project-Loki",
    year: "2025",
    role: "Backend engineer, team project",
    status: "Team project",
    summary:
      "A detective mystery game in Godot 4.5 with six LLM-roleplayed characters, each gated by server-authoritative evidence logic so the model can't hand out the solution.",
    tags: ["product", "ai"],
    stack: ["Godot 4.5", "FastAPI", "Motor", "MongoDB", "OpenAI API"],
    href: "/work/project-loki",
    githubHref: "https://github.com/luSteven01/Project-Loki",
    hasCaseStudy: true,
    thumbnail: "/work/project-loki/main-menu.webp",
  },
  {
    slug: "meditrek",
    index: 6,
    title: "MediTrek — HackHayward",
    year: "2025",
    role: "Hackathon team",
    award: "1st · Use of Perplexity/Sonar",
    summary:
      "AI medication recommendation platform — one combined Perplexity call returns OTC suggestions, do/don't care guidance, and nearby pharmacies from a ZIP code.",
    tags: ["ai", "product"],
    stack: ["Python", "FastAPI", "JavaScript", "Perplexity AI API", "Google Places API", "Vercel"],
    href: "/work/meditrek",
    demoHref: "https://meditrek.vercel.app/",
    githubHref: "https://github.com/driffe/Medication-Recommend",
    hasCaseStudy: true,
    thumbnail: "/work/meditrek/form.webp",
  },
  {
    slug: "test-automation-tool",
    index: 7,
    title: "Test Automation Tool",
    year: "2025",
    role: "Solo developer",
    summary:
      "Runs one question file against Claude, ChatGPT 4, and ChatGPT 3.5 side by side, scoring every reply on expected-keyword coverage instead of reading them by hand.",
    tags: ["ai", "tools"],
    stack: ["Python", "OpenAI API", "Anthropic API", "JSON"],
    href: "/work/test-automation-tool",
    demoHref: "https://www.youtube.com/watch?v=JZXYpMRs_uE",
    hasCaseStudy: true,
    thumbnail: "/work/test-automation-tool/runner.webp",
  },
  {
    slug: "ai-health-checker",
    index: 8,
    title: "AI Health Checker — AWS MCP & A2A Hackathon",
    year: "2025",
    role: "Hackathon team",
    summary:
      "Automated medication reminder system for elderly users, with a VAPI.ai voice interface and Twilio SMS notifications.",
    tags: ["ai", "tools"],
    stack: ["Python", "Flask", "VAPI.ai", "Claude AI", "Twilio"],
    href: "/work/ai-health-checker",
    githubHref: "https://github.com/driffe/A2A-hackathon",
    hasCaseStudy: true,
  },
  {
    slug: "autowise",
    index: 9,
    title: "Autowise — SpartUp Hackathon",
    year: "2025",
    role: "Hackathon team",
    award: "5th place",
    summary: "AI-powered car maintenance app built in four hours.",
    tags: ["ai", "web"],
    stack: ["Next.js", "TypeScript", "Perplexity AI API", "Mapbox API", "Netlify"],
    href: "/work/autowise",
    demoHref: "https://visionary-squirrel-309b11.netlify.app/",
    hasCaseStudy: true,
  },
  {
    slug: "personal-money-tracker",
    index: 10,
    title: "Personal Money Tracker",
    year: "2024",
    role: "Solo developer",
    summary:
      "Personal expense manager built in Next.js with a secure OAuth flow and a Firestore schema locked down by custom security rules.",
    tags: ["web"],
    stack: ["Next.js", "TypeScript", "Firebase", "OAuth", "TailwindCSS", "Vercel"],
    href: "/work/personal-money-tracker",
    demoHref: "https://army-money-tracker.vercel.app/",
    githubHref: "https://github.com/driffe/Army",
    hasCaseStudy: true,
  },
  {
    slug: "weather-app",
    index: 11,
    title: "Weather App",
    year: "2024",
    role: "Solo developer",
    summary: "Bilingual (KR/EN) weather app built as a PWA on the OpenWeatherMap API.",
    tags: ["web"],
    stack: ["Next.js", "TypeScript", "TailwindCSS", "PWA", "Vercel"],
    href: "/work/weather-app",
    demoHref: "https://weather-app-seyoungohs-projects.vercel.app/",
    githubHref: "https://github.com/driffe/weatherApp",
    hasCaseStudy: true,
  },
  {
    slug: "chrome-extension-suite",
    index: 12,
    title: "Chrome Extension Suite",
    year: "2023–2024",
    role: "Solo developer",
    summary:
      "Two published Chrome extensions built as single-purpose browser utilities: a moon-phase timer and a reaction-time tester.",
    tags: ["tools", "web"],
    stack: ["JavaScript", "HTML/CSS", "Chrome Extensions"],
    href: "/work/chrome-extension-suite",
    hasCaseStudy: true,
    group: [
      {
        title: "Moon Phase Timer",
        href: "https://chromewebstore.google.com/detail/moon-phase-timer/kkiikiidimhmaenmpdpfgkhoahkccjhm",
      },
      {
        title: "Reaction Time Test",
        href: "https://chromewebstore.google.com/detail/%EB%B0%98%EC%9D%91%EC%86%8D%EB%8F%84-%ED%85%8C%EC%8A%A4%ED%8A%B8/oefdnnlfjgoagefgnhfhffjgdbgipoin",
      },
    ],
  },
];

export const caseStudySlugs = work.filter((w) => w.hasCaseStudy).map((w) => w.slug);

export function getWorkBySlug(slug: string): WorkItem | undefined {
  return work.find((w) => w.slug === slug);
}
